#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# protect.py - self-decoding obfuscator for gamesense/LuaJIT scripts.
#
# Wraps a lua file in one or more layers of XOR + base64. Each layer emits a
# tiny stub that decodes its payload back to the previous layer at runtime and
# load()s it, so the cheat runs it normally while the file on disk / GitHub is
# an unreadable blob. This raises the bar against casual dumping; it is NOT
# cryptography (the key ships in the stub) and cannot stop a determined memory
# dump - no interpreted lua can.
#
#   python3 tools/protect.py <input.lua> <output.lua> [layers]
# ---------------------------------------------------------------------------
import sys, os, base64, random, string

def rid(n=None):
    n = n or random.randint(3, 6)
    return "_" + "".join(random.choice(string.ascii_letters) for _ in range(n))

def lua_bytes_literal(b: bytes) -> str:
    # decimal \ddd escapes inside a normal quoted string
    return '"' + "".join("\\%d" % c for c in b) + '"'

def xor(data: bytes, key: bytes) -> bytes:
    return bytes(data[i] ^ key[i % len(key)] for i in range(len(data)))

B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

def wrap_layer(src: bytes) -> str:
    key = bytes(random.randint(1, 255) for _ in range(random.randint(24, 48)))
    payload = base64.b64encode(xor(src, key)).decode()

    P, K, A, D, i, v, bits, nb, out, raw, s, f, ch, alpha = (rid() for _ in range(14))
    return (
        f'local {P}="{payload}"\n'
        f'local {K}={lua_bytes_literal(key)}\n'
        f'local {alpha}="{B64}"\n'
        f'local {A}={{}}\n'
        f'for {i}=1,#{alpha} do {A}[{alpha}:sub({i},{i})]={i}-1 end\n'
        f'local {bits},{nb},{out}=0,0,{{}}\n'
        f'for {i}=1,#{P} do\n'
        f' local {ch}={P}:sub({i},{i})\n'
        f' local {v}={A}[{ch}]\n'
        f' if {v} then\n'
        f'  {bits}={bits}*64+{v};{nb}={nb}+6\n'
        f'  if {nb}>=8 then {nb}={nb}-8;{out}[#{out}+1]=string.char(math.floor({bits}/2^{nb})%256);{bits}={bits}%(2^{nb}) end\n'
        f' end\n'
        f'end\n'
        f'local {raw}=table.concat({out})\n'
        f'local {s}={{}}\n'
        f'for {i}=1,#{raw} do {s}[{i}]=string.char(bit.bxor({raw}:byte({i}),{K}:byte(({i}-1)%#{K}+1))) end\n'
        f'local {f}=load(table.concat({s}))\n'
        f'if {f} then {f}() end\n'
    )

def main():
    if len(sys.argv) < 3:
        print("usage: protect.py <input.lua> <output.lua> [layers]")
        sys.exit(1)
    inp, outp = sys.argv[1], sys.argv[2]
    layers = int(sys.argv[3]) if len(sys.argv) > 3 else 2

    with open(inp, "rb") as fh:
        data = fh.read()

    banner = ("-- necrotool protected build. Generated by tools/protect.py.\n"
              "-- Do NOT edit; edit the source and re-run protect.py.\n").encode()

    cur = data
    for _ in range(max(1, layers)):
        cur = wrap_layer(cur).encode()

    with open(outp, "wb") as fh:
        fh.write(banner + cur)

    print(f"protected {inp} -> {outp}  ({len(data)} -> {len(cur)} bytes, {layers} layers)")

if __name__ == "__main__":
    main()
